<?php
return [
    'clubs' => [
        'title' => 'Sports Clubs',
        'singular' => 'Club',
        'table' => 'clubs',
        'alias' => 'c',
        'icon' => 'bi-shield-fill-check',
        'description' => 'Manage university sports clubs, coaches, venues and capacity.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'],
        'edit_roles' => ['admin'],
        'delete_roles' => ['admin'],
        'from' => 'clubs c',
        'select' => 'c.*',
        'order' => 'c.created_at DESC',
        'list_columns' => [
            'name' => 'Club', 'sport' => 'Sport', 'coach' => 'Coach', 'venue' => 'Venue', 'capacity' => 'Capacity', 'status' => 'Status'
        ],
        'search' => ['c.name', 'c.sport', 'c.coach', 'c.venue'],
        'fields' => [
            'name' => ['label' => 'Club name', 'type' => 'text', 'required' => true, 'placeholder' => 'e.g. NSBM Basketball Club'],
            'sport' => ['label' => 'Sport', 'type' => 'text', 'required' => true, 'placeholder' => 'Basketball'],
            'coach' => ['label' => 'Head coach', 'type' => 'text', 'required' => true],
            'venue' => ['label' => 'Primary venue', 'type' => 'text', 'required' => true],
            'training_days' => ['label' => 'Training days', 'type' => 'text', 'required' => true, 'placeholder' => 'Tue & Thu · 5:30 PM'],
            'capacity' => ['label' => 'Member capacity', 'type' => 'number', 'required' => true, 'min' => 1],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
        ],
    ],

    'memberships' => [
        'title' => 'Club Memberships',
        'singular' => 'Membership',
        'table' => 'memberships',
        'alias' => 'm',
        'icon' => 'bi-people-fill',
        'description' => 'Review student club applications and membership status.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'],
        'edit_roles' => ['admin'],
        'delete_roles' => ['admin', 'student'],
        'scope_field' => 'm.user_id',
        'owner_field' => 'user_id',
        'from' => 'memberships m JOIN users u ON u.id=m.user_id JOIN clubs c ON c.id=m.club_id',
        'select' => 'm.*, u.name AS student_name, u.student_id, c.name AS club_name',
        'order' => 'm.created_at DESC',
        'list_columns' => ['student_name' => 'Student', 'student_id' => 'Student ID', 'club_name' => 'Club', 'status' => 'Status', 'joined_at' => 'Joined'],
        'search' => ['u.name', 'u.student_id', 'c.name', 'm.status'],
        'fields' => [
            'user_id' => ['label' => 'Student', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, CONCAT(name, " · ", student_id) label FROM users WHERE role="student" ORDER BY name'],
            'club_id' => ['label' => 'Club', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, name label FROM clubs WHERE status="active" ORDER BY name'],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected']],
            'joined_at' => ['label' => 'Joined date', 'type' => 'date'],
        ],
    ],

    'training_sessions' => [
        'title' => 'Training Sessions',
        'singular' => 'Training Session',
        'table' => 'training_sessions',
        'alias' => 't',
        'icon' => 'bi-calendar2-week-fill',
        'description' => 'Plan and publish club training schedules.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin'],
        'from' => 'training_sessions t JOIN clubs c ON c.id=t.club_id',
        'select' => 't.*, c.name AS club_name',
        'order' => 't.session_date DESC, t.start_time DESC',
        'list_columns' => ['title' => 'Session', 'club_name' => 'Club', 'session_date' => 'Date', 'start_time' => 'Start', 'venue' => 'Venue', 'status' => 'Status'],
        'search' => ['t.title', 'c.name', 't.venue', 't.coach'],
        'fields' => [
            'club_id' => ['label' => 'Club', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, name label FROM clubs WHERE status="active" ORDER BY name'],
            'title' => ['label' => 'Session title', 'type' => 'text', 'required' => true],
            'session_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
            'start_time' => ['label' => 'Start time', 'type' => 'time', 'required' => true],
            'end_time' => ['label' => 'End time', 'type' => 'time', 'required' => true],
            'venue' => ['label' => 'Venue', 'type' => 'text', 'required' => true],
            'coach' => ['label' => 'Coach / trainer', 'type' => 'text', 'required' => true],
            'notes' => ['label' => 'Notes', 'type' => 'textarea'],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['scheduled' => 'Scheduled', 'completed' => 'Completed', 'cancelled' => 'Cancelled']],
        ],
    ],

    'matches' => [
        'title' => 'Matches & Fixtures',
        'singular' => 'Match',
        'table' => 'sports_matches',
        'alias' => 'sm',
        'icon' => 'bi-lightning-charge-fill',
        'description' => 'Manage fixtures, venues, opponents and match status.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin'],
        'from' => 'sports_matches sm JOIN clubs c ON c.id=sm.club_id',
        'select' => 'sm.*, c.name AS club_name',
        'order' => 'sm.match_date DESC, sm.start_time DESC',
        'list_columns' => ['club_name' => 'Club', 'opponent' => 'Opponent', 'competition' => 'Competition', 'match_date' => 'Date', 'venue' => 'Venue', 'status' => 'Status'],
        'search' => ['c.name', 'sm.opponent', 'sm.competition', 'sm.venue'],
        'fields' => [
            'club_id' => ['label' => 'Club', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, name label FROM clubs WHERE status="active" ORDER BY name'],
            'opponent' => ['label' => 'Opponent', 'type' => 'text', 'required' => true],
            'competition' => ['label' => 'Competition', 'type' => 'text', 'required' => true],
            'match_date' => ['label' => 'Match date', 'type' => 'date', 'required' => true],
            'start_time' => ['label' => 'Start time', 'type' => 'time', 'required' => true],
            'venue' => ['label' => 'Venue', 'type' => 'text', 'required' => true],
            'home_away' => ['label' => 'Fixture type', 'type' => 'select', 'required' => true, 'options' => ['home' => 'Home', 'away' => 'Away', 'neutral' => 'Neutral']],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['scheduled' => 'Scheduled', 'completed' => 'Completed', 'cancelled' => 'Cancelled']],
        ],
    ],

    'tournaments' => [
        'title' => 'Tournaments',
        'singular' => 'Tournament',
        'table' => 'tournaments',
        'alias' => 'tr',
        'icon' => 'bi-trophy-fill',
        'description' => 'Create tournaments and manage registration windows.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin'],
        'from' => 'tournaments tr', 'select' => 'tr.*', 'order' => 'tr.start_date DESC',
        'list_columns' => ['title' => 'Tournament', 'sport' => 'Sport', 'location' => 'Location', 'start_date' => 'Starts', 'registration_deadline' => 'Deadline', 'status' => 'Status'],
        'search' => ['tr.title', 'tr.sport', 'tr.location'],
        'fields' => [
            'title' => ['label' => 'Tournament title', 'type' => 'text', 'required' => true],
            'sport' => ['label' => 'Sport', 'type' => 'text', 'required' => true],
            'location' => ['label' => 'Location', 'type' => 'text', 'required' => true],
            'start_date' => ['label' => 'Start date', 'type' => 'date', 'required' => true],
            'end_date' => ['label' => 'End date', 'type' => 'date', 'required' => true],
            'registration_deadline' => ['label' => 'Registration deadline', 'type' => 'date', 'required' => true],
            'max_participants' => ['label' => 'Max participants', 'type' => 'number', 'required' => true, 'min' => 1],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['open' => 'Open', 'closed' => 'Closed', 'completed' => 'Completed', 'cancelled' => 'Cancelled']],
        ],
    ],

    'tournament_registrations' => [
        'title' => 'Tournament Registrations',
        'singular' => 'Tournament Registration',
        'table' => 'tournament_registrations',
        'alias' => 'rg',
        'icon' => 'bi-ticket-perforated-fill',
        'description' => 'Review individual and team tournament registrations.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin', 'student'],
        'scope_field' => 'rg.user_id',
        'owner_field' => 'user_id',
        'from' => 'tournament_registrations rg JOIN users u ON u.id=rg.user_id JOIN tournaments tr ON tr.id=rg.tournament_id',
        'select' => 'rg.*, u.name AS student_name, u.student_id, tr.title AS tournament_name',
        'order' => 'rg.created_at DESC',
        'list_columns' => ['student_name' => 'Student', 'tournament_name' => 'Tournament', 'team_name' => 'Team / Entry', 'status' => 'Status', 'created_at' => 'Registered'],
        'search' => ['u.name', 'u.student_id', 'tr.title', 'rg.team_name'],
        'fields' => [
            'tournament_id' => ['label' => 'Tournament', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, title label FROM tournaments ORDER BY start_date DESC'],
            'user_id' => ['label' => 'Student', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, CONCAT(name, " · ", student_id) label FROM users WHERE role="student" ORDER BY name'],
            'team_name' => ['label' => 'Team / entry name', 'type' => 'text'],
            'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected']],
        ],
    ],

    'results' => [
        'title' => 'Match Results',
        'singular' => 'Result',
        'table' => 'match_results',
        'alias' => 'r',
        'icon' => 'bi-bar-chart-fill',
        'description' => 'Record official scores, outcomes and match notes.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin'],
        'from' => 'match_results r JOIN sports_matches sm ON sm.id=r.match_id JOIN clubs c ON c.id=sm.club_id',
        'select' => 'r.*, c.name AS club_name, sm.opponent, sm.match_date, CONCAT(r.nsbm_score, " - ", r.opponent_score) AS scoreline',
        'order' => 'sm.match_date DESC',
        'list_columns' => ['club_name' => 'Club', 'opponent' => 'Opponent', 'match_date' => 'Date', 'scoreline' => 'Score', 'result' => 'Result', 'notes' => 'Notes'],
        'search' => ['c.name', 'sm.opponent', 'r.result'],
        'fields' => [
            'match_id' => ['label' => 'Match', 'type' => 'relation', 'required' => true, 'query' => 'SELECT sm.id, CONCAT(c.name, " vs ", sm.opponent, " · ", sm.match_date) label FROM sports_matches sm JOIN clubs c ON c.id=sm.club_id ORDER BY sm.match_date DESC'],
            'nsbm_score' => ['label' => 'NSBM score', 'type' => 'number', 'required' => true, 'min' => 0],
            'opponent_score' => ['label' => 'Opponent score', 'type' => 'number', 'required' => true, 'min' => 0],
            'result' => ['label' => 'Result', 'type' => 'select', 'required' => true, 'options' => ['won' => 'Won', 'draw' => 'Draw', 'lost' => 'Lost']],
            'notes' => ['label' => 'Match notes', 'type' => 'textarea'],
        ],
    ],

    'bookings' => [
        'title' => 'Facility & Equipment Bookings',
        'singular' => 'Booking',
        'table' => 'bookings',
        'alias' => 'b',
        'icon' => 'bi-building-check',
        'description' => 'Request and approve university sports facilities and equipment.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin', 'student'], 'edit_roles' => ['admin', 'student'], 'delete_roles' => ['admin', 'student'],
        'scope_field' => 'b.user_id',
        'owner_field' => 'user_id',
        'from' => 'bookings b JOIN users u ON u.id=b.user_id LEFT JOIN clubs c ON c.id=b.club_id',
        'select' => 'b.*, u.name AS student_name, c.name AS club_name',
        'order' => 'b.booking_date DESC, b.start_time DESC',
        'list_columns' => ['student_name' => 'Student', 'booking_type' => 'Type', 'item_name' => 'Facility / Equipment', 'booking_date' => 'Date', 'start_time' => 'Time', 'status' => 'Status'],
        'search' => ['u.name', 'b.item_name', 'b.booking_type', 'c.name'],
        'fields' => [
            'user_id' => ['label' => 'Student', 'type' => 'owner_relation', 'required' => true, 'query' => 'SELECT id, CONCAT(name, " · ", student_id) label FROM users WHERE role="student" ORDER BY name'],
            'club_id' => ['label' => 'Related club', 'type' => 'relation', 'required' => false, 'query' => 'SELECT id, name label FROM clubs WHERE status="active" ORDER BY name'],
            'booking_type' => ['label' => 'Booking type', 'type' => 'select', 'required' => true, 'options' => ['facility' => 'Facility', 'equipment' => 'Equipment']],
            'item_name' => ['label' => 'Facility / equipment', 'type' => 'text', 'required' => true, 'placeholder' => 'Indoor Court / Cricket Nets / Training Cones'],
            'booking_date' => ['label' => 'Booking date', 'type' => 'date', 'required' => true],
            'start_time' => ['label' => 'Start time', 'type' => 'time', 'required' => true],
            'end_time' => ['label' => 'End time', 'type' => 'time', 'required' => true],
            'purpose' => ['label' => 'Purpose', 'type' => 'textarea', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'admin_select', 'options' => ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected', 'cancelled' => 'Cancelled'], 'default' => 'pending'],
            'admin_note' => ['label' => 'Admin note', 'type' => 'admin_textarea'],
        ],
    ],

    'participation' => [
        'title' => 'Participation History',
        'singular' => 'Participation Record',
        'table' => 'participation',
        'alias' => 'p',
        'icon' => 'bi-activity',
        'description' => 'Track student attendance, competitions and performance points.',
        'roles' => ['admin', 'student'],
        'create_roles' => ['admin'], 'edit_roles' => ['admin'], 'delete_roles' => ['admin'],
        'scope_field' => 'p.user_id',
        'from' => 'participation p JOIN users u ON u.id=p.user_id JOIN clubs c ON c.id=p.club_id',
        'select' => 'p.*, u.name AS student_name, u.student_id, c.name AS club_name',
        'order' => 'p.event_date DESC',
        'list_columns' => ['student_name' => 'Student', 'club_name' => 'Club', 'event_type' => 'Type', 'event_name' => 'Event', 'event_date' => 'Date', 'points' => 'Points'],
        'search' => ['u.name', 'c.name', 'p.event_type', 'p.event_name'],
        'fields' => [
            'user_id' => ['label' => 'Student', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, CONCAT(name, " · ", student_id) label FROM users WHERE role="student" ORDER BY name'],
            'club_id' => ['label' => 'Club', 'type' => 'relation', 'required' => true, 'query' => 'SELECT id, name label FROM clubs ORDER BY name'],
            'event_type' => ['label' => 'Activity type', 'type' => 'select', 'required' => true, 'options' => ['training' => 'Training', 'match' => 'Match', 'tournament' => 'Tournament', 'volunteer' => 'Volunteer']],
            'event_name' => ['label' => 'Event / activity', 'type' => 'text', 'required' => true],
            'event_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
            'points' => ['label' => 'Performance points', 'type' => 'number', 'required' => true, 'min' => 0],
            'remarks' => ['label' => 'Remarks', 'type' => 'textarea'],
        ],
    ],
];
