<?php use App\Core\Auth; require __DIR__ . '/../partials/header.php'; ?>
<div class="page-heading reveal"><div><span class="eyebrow">Account</span><h1>My Profile</h1><p>Keep your personal information and password up to date.</p></div></div>
<div class="profile-grid">
    <section class="profile-card panel reveal">
        <div class="profile-hero"><span class="avatar xl"><?= e(initials($profileUser['name'])) ?></span><div><h2><?= e($profileUser['name']) ?></h2><p><?= e($profileUser['email']) ?></p><span class="status-pill success"><?= e(ucfirst($profileUser['role'])) ?></span></div></div>
        <div class="profile-meta"><div><span>Student ID</span><strong><?= e($profileUser['student_id'] ?: '—') ?></strong></div><div><span>Faculty</span><strong><?= e($profileUser['faculty'] ?: '—') ?></strong></div><div><span>Member since</span><strong><?= e(format_date($profileUser['created_at'])) ?></strong></div></div>
    </section>
    <section class="panel reveal delay-1"><div class="panel-head"><div><span class="eyebrow">Personal details</span><h2>Edit profile</h2></div></div><form method="post" action="<?= e(url('profile')) ?>" class="form-grid"><?= csrf_field() ?><label class="field field-span-2"><span>Full name</span><input type="text" name="name" value="<?= e($profileUser['name']) ?>" required></label><label class="field"><span>Student ID</span><input type="text" name="student_id" value="<?= e($profileUser['student_id']) ?>"></label><label class="field"><span>Faculty</span><input type="text" name="faculty" value="<?= e($profileUser['faculty']) ?>"></label><div class="field-span-2 form-actions"><button class="btn btn-primary" type="submit"><i class="bi bi-check2-circle"></i> Save profile</button></div></form></section>
    <section class="panel reveal span-12"><div class="panel-head"><div><span class="eyebrow">Security</span><h2>Change password</h2></div></div><form method="post" action="<?= e(url('profile_password')) ?>" class="form-grid"><?= csrf_field() ?><label class="field"><span>Current password</span><input type="password" name="current_password" required></label><label class="field"><span>New password</span><input type="password" name="new_password" minlength="8" required></label><label class="field"><span>Confirm new password</span><input type="password" name="new_password_confirmation" minlength="8" required></label><div class="field form-actions align-end"><button class="btn btn-secondary" type="submit"><i class="bi bi-shield-lock"></i> Update password</button></div></form></section>
</div>
<?php require __DIR__ . '/../partials/footer.php'; ?>
