<?php require __DIR__ . '/../partials/header.php'; ?>
<div class="page-heading reveal"><div><span class="eyebrow">Decision support</span><h1>Reports & Analytics</h1><p>Participation, performance and booking insights across the sports community.</p></div><button class="btn btn-ghost" type="button" onclick="window.print()"><i class="bi bi-printer"></i> Print report</button></div>
<div class="dashboard-grid">
<section class="panel span-8 reveal"><div class="panel-head"><div><span class="eyebrow">Club performance</span><h2>Engagement leaderboard</h2></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Club</th><th>Sport</th><th>Members</th><th>Activities</th><th>Points</th></tr></thead><tbody><?php foreach($clubPerformance as $row): ?><tr><td><strong><?= e($row['name']) ?></strong></td><td><?= e($row['sport']) ?></td><td><?= (int)$row['members'] ?></td><td><?= (int)$row['activities'] ?></td><td><span class="points-badge"><?= (int)$row['points'] ?> pts</span></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="panel span-4 reveal delay-1"><div class="panel-head"><div><span class="eyebrow">Match outcomes</span><h2>Results mix</h2></div></div><div class="donut-wrap" data-donut><?php $total=array_sum(array_column($resultBreakdown,'total')); foreach($resultBreakdown as $r): $pct=$total?round($r['total']/$total*100):0; ?><div class="bar-row"><div><span><?= e(ucfirst($r['result'])) ?></span><strong><?= $pct ?>%</strong></div><div class="progress"><span style="width:<?= $pct ?>%"></span></div></div><?php endforeach; ?></div></section>
<section class="panel span-5 reveal"><div class="panel-head"><div><span class="eyebrow">Bookings</span><h2>Status breakdown</h2></div></div><div class="metric-list"><?php foreach($bookingBreakdown as $r): ?><div><span class="status-pill <?= e(status_class($r['status'])) ?>"><?= e(ucfirst($r['status'])) ?></span><strong><?= (int)$r['total'] ?></strong></div><?php endforeach; ?></div></section>
<section class="panel span-7 reveal delay-1"><div class="panel-head"><div><span class="eyebrow">Last six months</span><h2>Participation activity</h2></div></div><div class="mini-chart"><?php $max=max(array_column($monthlyParticipation,'total') ?: [1]); foreach($monthlyParticipation as $r): ?><div class="chart-col"><span style="height:<?= max(12,round($r['total']/$max*100)) ?>%"></span><small><?= e(date('M', strtotime($r['month'].'-01'))) ?></small></div><?php endforeach; ?></div></section>
</div>
<?php require __DIR__ . '/../partials/footer.php'; ?>
